name: DotNet Development

on:
  pull_request:
    branches: [ development ]
  push:
    branches: [ development ]

  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v3
      - uses: microsoft/setup-msbuild@v1.1
        with:
          msbuild-architecture: x64
      - uses: nuget/setup-nuget@v1.0.7
        with:
          nuget-version: 'latest'

      - name: NuGet restore
        run: nuget restore src/WPFUI.sln

      - name: Build
        run: msbuild src/WPFUI.sln -p:Configuration=Release -m

      - name: Publish net60
        uses: actions/upload-artifact@v3
        id: publish_net6
        with:
          name: WPFUI_DEMO-NET6
          path: |
            src/WPFUI.Demo/bin/Release/net6.0-windows10.0.22000.0
